# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipcode',
            old_name='zipcode',
            new_name='code',
        ),
    ]
