# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 04:23
from __future__ import unicode_literals

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160801_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='code',
        ),
        migrations.AddField(
            model_name='zipcode',
            name='zipcode',
            field=models.CharField(default='', help_text='우편번호를 입력', max_length=10, validators=[blog.validators.ZipCodeValidator]),
            preserve_default=False,
        ),
    ]
