# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160801_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipcode',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
